trigger:
- master

pool:
  name: Default
  demands:
    - agent.name -equals vm-docker

steps:

# Step 1: Verify environment
- task: CmdLine@2
  displayName: 'Verify Agent Environment'
  inputs:
    script: |
      echo "Running on agent: $(Agent.Name)"
      echo "Current directory: $(Build.SourcesDirectory)"
      uname -a
      df -h
      whoami
      mvn --version

# Step 2: Build the Maven project (pom.xml should exist)
- task: CmdLine@2
  displayName: 'Maven Clean Package'
  inputs:
    script: |
      echo "Running Maven build"
      mvn clean package

# Step 3: Deploy to Azure Artifacts
- task: CmdLine@2
  displayName: 'Maven Deploy to Azure Artifacts'
  inputs:
    script: |
      echo "Deploying to Azure Artifacts Feed"
      mvn deploy
